# 📌NumPy: The absolute basics📝
* NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. 
* The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional `ndarray`, and a large library of functions that operate efficiently on these data structures.

## Why use Numpy?🤔
* Python lists are excellent, general-purpose containers. 
* They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.
* We can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. 
* NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

### Import⏬

In [2]:
import numpy as np

### Speed🚀


In [1]:
import time
import random

start_time = time.time()
a = [random.randint(0, 100000) for i in range(1000)]
b = [random.randint(0, 100000) for i in range(1000)]
c = []

for i in range(len(a)):
    c.append(a[i] ** b[i])

end_time = time.time()

print(f"Time taken:{end_time - start_time:.5f} seconds")

Time taken:19.88115 seconds


In [3]:
start_time = time.time()

a = np.random.randint(0, 100000, 1000)
b = np.random.randint(0, 100000, 1000)

c = a**b

end_time = time.time()

print(f"Time taken:{end_time - start_time:.5f} seconds")

Time taken:0.00117 seconds


## Arrays🔢: Intro
* In computer programming, an array is a structure for storing and retrieving data. 
* We often talk about an array as if it were a grid in space, with each cell storing one element of the data.
* In NumPy, this idea is generalized to an arbitrary number of dimensions, <br>and so the fundamental array class is called ndarray: it represents an **“N-dimensional array”**.

## Arrays fundamentals🔖

* One way to initialize an array is using a Python sequence, such as a list. For example:

In [5]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

* Elements of an array can be accessed in various ways. 
* For instance, we can access an individual element of this array as we would access <br> an element in the original list: using the integer index of the element within square brackets.

In [6]:
a[0]


1

**Note📍**
* As with built-in Python sequences, NumPy arrays are **“0-indexed”**: the first element of the array is accessed using index `0`, not `1`.

* Like the original list, the array is mutable.

In [7]:
a[0] = 10
a

array([10,  2,  3,  4,  5])

* Also like the original list, Python slice notation can be used for indexing.


In [12]:
# Slice array
b = a[1:3]
b

array([2, 3])

* One major difference is that slice indexing of a list copies the elements into a new list, <br> but slicing an array returns a **_view_**: an object that refers to the data in the original array. 
* The original array can be mutated using the view.
* Two- and higher-dimensional arrays can be initialized from nested Python sequences

In [13]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* Accessing value from n-dimensional array

In [15]:
a1[1, 2]

6

## Array attributes🔖

* The number of dimensions of an array is contained in the `ndim` attribute

In [16]:
print(f"{a1}\n Dimension: {a1.ndim}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 Dimension: 2


* The `shape` of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [17]:
a1.shape

(3, 3)

* The fixed, total number of elements in array is contained in the `size` attribute.

In [18]:
a1.size

9

* Arrays are typically **“homogeneous”**, meaning that they contain elements of only one **“data type”**. 
* The data type is recorded in the `dtype` attribute.

In [19]:
a1.dtype

dtype('int64')

## Creating basic array🔖
This section covers `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`

* Besides creating an array from a sequence of elements, you can easily create an array filled with `0`’s

In [21]:
a2 = np.zeros((3, 3))
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* An array filled with `1`’s

In [23]:
a2 = np.ones((3, 3))
a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* The function empty creates an array whose initial content is random and depends on the state of the memory. 
* The reason to use `empty` over `zeros` (or something similar) is speed - just make sure to fill every element afterwards❗

* You can create an array with a range of elements

* You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval

## Sorting and Concatenate🔖

* Sorting an array is simple with `np.sort()`. 
* You can specify the axis, kind, and order when you call the function.

In [28]:
# sort array
a = np.array([3, 1, 2, 4, 5])
a.sort()
a

array([1, 2, 3, 4, 5])

* You can concatenate them with `np.concatenate()`

In [29]:
# array concatenation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6])

## Shape and size of an array🔖
**_This section covers_** `ndarray.ndim`, `ndarray.size`, `ndarray.shape`

* `ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

* `ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

* `ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is `(2, 3)`

## Indexing and Slicing🔖

* You can index and slice NumPy arrays in the same ways you can slice Python lists<br>
  ![index_slice](/workspaces/Fit-Flow/Python/np_indexing.png)

## Creating an array from existing data🔖

**_This section covers slicing and indexing,_** `np.vstack()`, `np.hstack()`, `np.hsplit()`, `.view()`, `copy()`

* You can easily create a new array from a section of an existing array.
* You can create a new array from a section of your array any time by specifying where you want to slice your array

In [32]:
# Array np.vstack() usage
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a, b))
print(c)
c = np.hstack((a, b))
c

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

* You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, `a1` and `a2`

* You can stack them vertically with `vstack`

* Or stack them horizontally with `hstack`

* Using the `copy` method will make a complete copy of the array and its data

## Basic array operations🔖

* Once you’ve created your arrays, you can start to work with them. 
* Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”
![operation](/workspaces/Fit-Flow/Python/np_array_dataones.png)

* You can add the arrays together with the plus sign
![add](/workspaces/Fit-Flow/Python/np_data_plus_ones.png)

* You can, of course, do more than just addition
![moreoperations](/workspaces/Fit-Flow/Python/np_sub_mult_divide.png)

* In an array, you’d use `sum()`. This works for 1D arrays, 2D arrays, and arrays in higher dimensions.